version: "3"
services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=lifecaldb
            - POSTGRES_USER=lifecal_user
            - POSTGRES_PASSWORD=lifecal_pass
    comments:
        container_name: comments
        build: ./backend/middlewares/comments
        restart: always
        ports: 
            - "5000:5000"