name: Node.js CI
on: [push]
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
      - name: Install dependencies
        run: |
          cd frontend
        run: npm install
      - run: npm run build --if-present
      - run: npm test